### ISSUE TITLE
Clarification on the XhciPortLimit quirk (Especially because it is getting removed)

### ISSUE THREAD

**Issue by DMNerd** [dortania/bugtracker#161]
This has to do with the PostInstall/Install guides.

My problem is the absence of information on the XhciPortLimit quirk.
1) In the Install guide, you are explicitltly told to enable it and what it is - all good
2) In the post install USB map section, there is a lack of clarifycation on wheter this quirk should be then set to false. Only that we don't need it. I find this a bit inconsistent and on even my 11 or so readtrough I have not understand this imidiately (Whis could be a bit on me but I don't think it is entirely my fault as I understand EVERYTHING ELSE completely).
 
More so, the way this quirk's name is confusing as XhciPortLimit set to true implies that the number of ports is being limited, while what I gather from the documentation on OC's side (which is just as confusing) is not true.

As this is a issue that could make the difference between build booting or not, I feel this should be clarified, ideally before 11.3 comes out.

Thank you for your work!

**Comment by khronokernel** [comment]
Hello, regarding your points:
> there is a lack of clarifycation on wheter this quirk should be then set to false.

We actually do mention this information in the intro and manual mapping guide
* [Discussing the quirk itself and its harms](https://dortania.github.io/OpenCore-Post-Install/usb/#macos-and-the-15-port-limit)
  * > And now when we take into account the quirk XhciPortLimit, you can see why data corruption can happen. As we're pushing past the 0xF limit and going into someone else's space. So avoid this quirk when possible.
* [Instructions to disable the quirk when finished mapping to verify results](https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html#cleaning-up)
  * > XhciPortLimit(Under Kernel -> Quirks)
Now that we're finally under the 15 port limit, we no longer need this hacky fix

Could you elaborate more where this info ma be missing and where it should be present? 

Regarding the semi-automated Intel mapping guide, our team members currently do not have time to rewrite the entire file since USBmap.py's rewrite.

Regarding the USBmap.py guide we link, we don't maintain the repo so information on the [README.md](https://github.com/corpnewt/USBMap/blob/master/README.md) would need to be discussed with the author(CorpNewt)

**Comment by DMNerd** [comment]
Hello. I found the info most lacking in the USBmap guide. But i understand from what you wrote that that is more or less problem of the age of that part. 

But my problem is more semantical really. I think that there should be clarification on the quirk name (as I explained XhciPortLimit true implies more or less that the ports are limited while they actually aren't, since setting it to true actually disabled the setting). And the second point is that in the usb guide it should explicitly say to set it to false after mapping, to keep consistency with the rest of the guide.

Is that enough of an explanation? Sorry if this seems as unimportant, but as someone who's native language is not English I can see people who's English might not be as good as mine getting confused with those slight issues.

**Comment by DMNerd** [comment]
'XhciPortLimit(Under Kernel -> Quirks)
Now that we're finally under the 15 port limit, we no longer need this hacky fix' 

This part especially could dirt say the setting. The absence of the -> false in the heading makes it a bit inconsistent when reading the rest. It might be a nitpick though.

**Comment by khronokernel** [comment]
Resolved in master https://github.com/dortania/OpenCore-Post-Install/commit/1d8024f2b8ef46d873c43c90e1be74168beea5fe

**Comment by DMNerd** [comment]
Thank you very much
