### ISSUE TITLE
Launcher Control: initial vs post-install configuration

### ISSUE THREAD

**Issue by rowild** [dortania/bugtracker#169]
* Guide(s) in question
Settings up Launcher option / Using Launcher option (the menu entry is different from the real topic header)

* Link to page(s) with the issue
https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html

* Clearly explain the issue(s) with the page(s) (if there is a visual issue, a screenshot is required)
During the initial instal routine, the "LauncherOption" is set to "disabled". In the post-install it is then set to "Full". I would like to know if these steps are required that way? Or if "LauncherOption" can be set to "Full" already before the initial install routine? If not, why?
I ask, because it occurs as a general question when reading the docu, but also, because there are many reports out there that complain that after a NVRAM reset OC cannot be started anymore and Windows takes precedence. Would this probably be a solution to that problem or are those totally unrelated?

**Comment by khronokernel** [comment]
> During the initial instal routine, the "LauncherOption" is set to "disabled". In the post-install it is then set to "Full". I would like to know if these steps are required that way? Or if "LauncherOption" can be set to "Full" already before the initial install routine? If not, why?

Makes little sense to setup LaucherOption on a USB that you'll move the EFI from afterwards. Makes more sense to setup LauncherOption on an installed OS drive

> many reports out there that complain that after a NVRAM reset OC cannot be started anymore and Windows takes precedence. Would this probably be a solution to that problem or are those totally unrelated?

It could help, but the main cause is that resetting NVRAM also resets the BIOS's boot options. LauncherOption is reinstalled into NVRAM right after NVRAM reset is done in OpenCore's menu, so avoids the headache of having to re-enable OpenCore as the top boot entry in the BIOS

I have not heard of reports that OpenCore is permanently not bootable after NVRAM reset, there's likely other issues like BOOTx64.efi has been removed/modified by the user or Windows

**Comment by dreamwhite** [comment]
>     * During the initial instal routine, the "LauncherOption" is set to "disabled". In the post-install it is then set to "Full". I would like to know if these steps are required that way? Or if "LauncherOption" can be set to "Full" already before the initial install routine? If not, why?

First of all let me write a small brief (gently took from [OpenCore's Configuration.pdf](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf)) explaining in short terms what is `LauncherOption` (also known previously as `BootStrap`) and why you'd need it:

> This option allows integration with third-party operating system installation and upgrades (which may overwrite the `\EFI\BOOT\BOOTx64.efi `file).

Basically let's assume that you have a dual-boot (especially with a single drive) of macOS and Linux/Windows. Let's suppose that Windows, for whatever reason decides to perform a system update and overwrites the `\EFI\BOOT\BOOTx64.efi` file which is essential to boot OpenCore. Without `LauncherOption` you should restore back the file and repeat this process for each time when Windows decides to update itself. 

With `LauncherOption` you won't need to worry about that since it:

> Register the launcher option in the firmware preferences for persistence

According to [acidanthera's bugtracker's issue 1222 vit9696's comment](https://github.com/acidanthera/bugtracker/issues/1222#issuecomment-739241310) (I lost a finger while adding quotes xD), some firmwares may have problems with Bootstrap (which is now renamed onto `Launcher`).
Those problems may be seen usually on older motherboards (like the Gigabyte Z87 motherboard mentioned in the linked issue). I don't know what's your hardware neither what kind of BIOS you have but if you have an Insyde BIOS, according to [OpenCore's Configuration.pdf LauncherOption description](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) you should opt for `Short` value of `LauncherOption` instead of `Full`.

![image](https://user-images.githubusercontent.com/17933708/110222707-7d94c380-7ed4-11eb-8fae-e1882a899a71.png)

As @khronokernel rightly wrote, it makes more sense setting `LauncherOption` to `Disabled` and only after you configured your drive and copied the EFI folder onto it, can set it back to `Full` (or `Short` for the reasons above).

Personally (and here I can be beaten by khronokernel 😆), I leave `LauncherOption` to `Full` and whenever I need to boot with a USB drive to do tests, I do a preventive NVRAM Reset (if you're asking how to do it, just enable `AllowNvramReset` and launch it when reaching OpenCore's boot-picker). Probably this isn't the right way to do the tests, but never had issue with it before, as when I reset NVRAM it clears all the UEFI boot-entries.

The main reason is that, given that you have `LauncherOption` value other than `Disabled` and you booted at least once OpenCore, if you give a quick look at your boot-menu entries you'll find an entry called `OpenCore`. This entry is linked to OpenCore's files (`BOOTx64.efi` (here I'm a little bit uncertain. Please khronokernel correct me if I'm wrong)) of the booting drive (e.g. if you boot OpenCore with `LauncherOption` enabled with your USB drive, OpenCore will create an entry pointing to the USB drive and sets it as the first entry of your boot priority).

Hope that we ( **communism intensifies** ) clarified your doubts ^^
