### ISSUE TITLE
Gigabyte RX 560 - HDMI 2.0 Flickering 

### ISSUE THREAD

**Issue by danchristian12** [dortania/bugtracker#232]
Hi all, recently got a RX 560 but my second display is flickering which is a 4K@60hz running over HDMI, but it keeps flickering off then going purple slightly and turning off for 1 second then back on wondering if anyone would know a fix for this?

The Flicker only occurs when using a HDMI 2,0 port on my Samsung U28E590D 4K monitor but when using the HDMI 1.4 port its abousltely fine no flickering  using a Gigabyte RX 560 4GB this issue does resolve after using the Monitor after 1 hour but it randomly tries to do the same thing inbetween being back to 'normal' It's as if theres a connector issue but the monitors are fine on my Windows Hard drive.

Below are attachments 

wondering if there is any insight to fix this? as it's making it unbearable to use on my 4K monitor
[opencore-2021-08-29-194005.txt](https://github.com/dortania/bugtracker/files/7073174/opencore-2021-08-29-194005.txt)
https://share.icloud.com/photos/0XjqE7P-dRL-qwMl3nD9_-x9g
https://share.icloud.com/photos/0XjqE7P-dRL-qwMl3nD9_-x9g

**Comment by TheHackGuy** [comment]
I know this works for IGPU but not sure about dgpu:
try adding the "enable-hdmi20" to your gpu path inside the config plist. GPU path can be found with gfxutil

**Comment by danchristian12** [comment]
With what data entries guessing adding -Cdfon to boot args too?

**Comment by TheHackGuy** [comment]
What do you mean with the data entries?

You can use -cdfon boot arg or the enable-hdmi20 in the gpu device path

**Comment by danchristian12** [comment]
Tried both of these still no luck

**Comment by ArchCryptonIO** [comment]
I have two monitors. One of them supports 1080p 165hz and and the other 4k 60Hz. As information, the way iGPU works is not the same as how dGPU works. iGPUs mostly have a maximum 60Hertz refresh rate while dGPUs support more than that amount. The way the iGPU works on monitors that support 4k 60Hz is very good as both support same refresh rate. For example UHD630 + 4k Monitor.

While dGPU is capable more than 60Hz. What will happen, the 60Hz 4k Monitor will be laggy if using a dGPU.As an example RX 6700 XT. This dGPU works well with Freesync only at 120Hz. I attach the picture below as an example. 

![240498703_366034071686577_9068643738926860150_n](https://user-images.githubusercontent.com/86180725/131455716-4ee7f73d-c3c4-4918-8131-c5093e49e9e5.png)

Even i have RX580 and RX5500Xt not work well on 4k 60Hz. Resolution does not have any effect because most all platforms support all types of resolutions depending on the dGPU. A low refresh rate will cause problems for the dGPU for this reason. Easier if you have a 4k monitor that supports a refresh rate of at least 75hz to try. Even better if you have 4k monitor that supports 120hz to 165hz (If any).

**Comment by danchristian12** [comment]
Ah okay so no real solution for this then?

**Comment by danchristian12** [comment]
My best bet might just be using the 1.4 and using it low resolution 1440p solution

**Comment by ArchCryptonIO** [comment]
@danchristian12 this problem can be sure as hardware issues. Yup, Lower Res is temporary fix for that. Permanent fix is to use 4k monitor which support above 60Hz.  IDK if someone other than me can explain other solution.  In windows, you can overclock refresh rate from 60Hz to 75Hz. However, this will cause your monitor lifespan shorter. I dont recommend that.

**Comment by PMheart** [comment]
Hello! Please use forums for support.
