### ISSUE TITLE
Inappropriate blames on one-key-cpufriend

### ISSUE THREAD

**Issue by stevezhengshiqi** [dortania/bugtracker#267]
* Guide(s) in question: Fixing Sleep - Fixing CPU Power Management
* Link to page(s) with the issue: https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#fixing-cpu-power-management
* Clearly explain the issue(s) with the page(s):

> Tools like [one-key-cpufriend (opens new window)](https://github.com/stevezhengshiqi/one-key-cpufriend) are known for creating bad frequency vectors

It seems like many people blame their sleep issues on my [one-key-cpufriend](https://github.com/stevezhengshiqi/one-key-cpufriend) for "bad frequency vectors". Many hackintoshers and I did thorough tests on every models in the list https://github.com/stevezhengshiqi/one-key-cpufriend/blob/main/one-key-cpufriend.sh#L21-L60 and clearly listed out all the LFM and EPP scenarios. Those who have sleep issues are mostly like:
- Generate their `CPUFriendProvider.kext` on an old macOS, and use the old CPUFriendProvider.kext upgrading to newer macOS version, which for sure will create problems. Apple may change frequency vector for even small macOS upgrades. Ridiculously, some of them use their **Big Sur** version `CPUFriendProvider` on **Monterey** version, which will let their machine run outdated frequency vectors. 

- Use other people's `CPUFriendProvider.kext`. Same as above, using same CPU does not prove one to use other's `CPUFriendProvider.kext`. macOS version, SMBIOS, iGPU, ... should all be considered carefully before using other people's kext. You don't know what macOS version other people used when they generated their `CPUFriendProvider.kext`.

These two people are more likely to blame their user mistakes on my script, which is a very unfortunate misunderstanding for me.
**User should not use `CPUFriendProvider` when they upgrade macOS version(even like 12.3 to 12.3.1), and they should generate new `CPUFriendProvider` after the upgrade**

* Include possible fixes
  * Correct those unreasonable blame on that guide page.
  * Add a disclaimer for `CPUFriend` to warn users that they need to generate new `CPUFriendProvider` for each macOS upgrade
    * https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#using-cpu-friend needs to be modified
  * As @PMheart and I both agreed, it is actually **NOT** recommended to use `CPUFriend` to tune PM for most users. XCPM is a dynamic PM mechanism, which means users do not need to tune it for most cases.

Sorry for my a bit tough tone in this issue, thank you all for maintaining this amazing guide for such long time.

**Comment by PMheart** [comment]
Hello! Ideally we can patch `FrequencyVectors` in CPUFriend as is done by [one-key-cpufriend](https://github.com/stevezhengshiqi/one-key-cpufriend) or [CPUFriendFriend](https://github.com/corpnewt/CPUFriendFriend). However, I doubt this is really worth the progress, because:
- As discouraged in [Instructions.md#warning](https://github.com/acidanthera/CPUFriend/blob/master/Instructions.md#warning), CPUFriend is generally not needed on modern CPU models;
- The actual case where CPUFriend may be useful is those unsupported (e.g. Broadwell-E) models with `MacPro6,1` SMBIOS, on which `FrequencyVectors` and thus CPUFriend is required to handle the injection.

While the users in the second category are reasonably rare, and the other XCPM patches for them need to be maintained from time to time as well, I do not think it is really worth it to work on this either; they can just copy-paste a new copy of `FrequencyVectors` from newer releases.

**Comment by PMheart** [comment]
I took a quick look at https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#using-cpu-friend, and would like to point out that:
- `X86PlatformPlugin` is also used by Ivy Bridge, however the power management data is named `StepContextDict` and used by `AICPUPM`, instead of `FrequencyVectors` and `XCPM`;
- CPUFriend can also be paired with the legacy `ACPI_SMC_Plugin` for power management replacement, though I have never seen anyone testing on this.

The only thing worth mentioning in this part is for those high-end users using `MacPro6,1`, who will replace `StepContextDict` with `FrequencyVectors` to be paired with XCPM I think.

**Comment by dhinakg** [comment]
Started working on this at dortania/OpenCore-Post-Install#111

**Comment by PMheart** [comment]
Hello! I have left my comments there.
