### ISSUE TITLE
Typo in Dortania guide (read issue desc for more info)

### ISSUE THREAD

**Issue by jw25116** [dortania/bugtracker#272]
Link: https://dortania.github.io/OpenCore-Multiboot/oc/win.html#dualbooting-with-windows

Where: 2nd Paragraph from title/top of the page or direct link (https://dortania.github.io/OpenCore-Multiboot/oc/win.html#solution-1-if-windows-is-not-picked-up-automagically-add-the-following-to-your-config-plist)

Text with error:
“Solution 1: If Windows is not picked up automagically, add the following to your config.plist”

Error change ‘automagically’ to ‘automatically’

**Comment by jw25116** [comment]
Additional note:
Someone writing this page didn’t get enough sleep or must’ve been drunk because they lacked a severe amount of capitalisation on the page listed above

**Comment by FishyFlower** [comment]
The word 'automagically' is a part of AppleSpeak (used to describe something happening out of the box, without user intervention, somehow magically for a standard user), and it's even picked up by Dictionary embedded in macOS: select it in Safari, then right click and choose Look Up. I see no reason to change it, even more, I think since we're using Apple's software it's even a better choice. 

And about capitalization, I guess it was written as a "dirty" note how to do this, not as a step-by-step guide, so I believe it's pending a rewrite anyway.
