### ISSUE TITLE
[Hardware] Supported motherboards

### ISSUE THREAD

**Issue by dreamwhite** [dortania/bugtracker#50]
Hi there,
many thanks for your fantastic [hardware buyers guide](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/). 
But there's one thing I'm having difficulties to understand: 

In the "Motherboards: chipset and brands to avoid" ([link](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Motherboard.html#motherboards)), only Intel ones motherboards are listed and not the AMD ones (except the "the only motherboard not supported at all is B550"). Why? What does this mean? Every AMD motherboard is supported or there are a few precautions when buying and AMD motherboard, such as "avoid MSI for weird memory layout etc..."? 
Many thanks and sorry if this issue is invalid :)

**Comment by khronokernel** [comment]
AMD motherboards in general are pretty garbage, mostly because they require a boat load of patching with their CPU. B550 however won't boot in general, specifics seem kernel related but most in the AMD community don't know much about the process so no progress has been made.

But regarding the actual issue, it's quite odd there's no mention of how motherboard support on AMD works. I believe it was there before but unsure where its gone, so will do some cleanup on that page. Thanks for pointing that out!

**Comment by dreamwhite** [comment]
@khronokernel a progress has been made for B550 compatibility: it seems like that B550 follows new ACPICA rules, which defines the processors no longer as ProcessorObj, but as DeviceObj. 

Btw, do you have any news about AMD motherboards? Please let me know

**Comment by khronokernel** [comment]
It's listed all over the guides...

* https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html
* https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Motherboard.html

**Comment by dreamwhite** [comment]
![image](https://user-images.githubusercontent.com/17933708/92261288-7c5cec80-eed9-11ea-9e1b-dd04a89b2df3.png)

Excuse me but I don't see a clear "main brands to avoid with AMD", but I'll take it as "take any AMD motherboard it will work".
Thank you so much

**Comment by khronokernel** [comment]
> Pretty much all AMD motherboards are unfavourable due to the numerous hacks required to boot, however the brand itself won't affect support very much with macOS.

https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Motherboard.html
