### ISSUE TITLE
[AMD] Stutter on mouse shape change

### ISSUE THREAD

**Issue by KirillStomdevice** [dortania/bugtracker#68]
system: x570 steel legend (latest bios), ryzen 3600x, 5600 xt gigabyte gaming oc(latest vbios)
efi : https://gofile.io/d/mTUS1B

Whenever there is a mouse shape change(quickly hovering a list of links or channels in discord), there is considerable stutter and high windowserver usage, the problem is not really noticeable when using one monitor but using 2 makes it quite unbearable.

Using mousecape (https://github.com/alexzielenski/Mousecape), and changing all the mouse to shape to the same one mitigate the stuttering considerably.

possibly related stuff:
when loading macos the 2nd monitor loads the background image before the main monitor loads the login window(stays black for 2-5 secs).
only one dp port will work for the main monitor(in 5500xt it was dp 1, in 5600xt it is dp3).
the second monitor is connected using hdmi when i disconnected the dp display the issue stays even though i am using only one monitor(repluging dp monitor and unpluging the hdmi mitigate the issue).
will try get a dp cable for the second monitor but since the other ports dont work with one display i assume they wont with 2.
EDIT: in my case i use only one gpu but there is a similar post here : https://amd-osx.com/forum/viewtopic.php?t=9112
EDIT2: tried the same gpu with a z97-c and 4690k(https://gofile.io/d/8qI1rr efi, didnt add whatevergreen args, simply changed main display gpu in bios to pcie), the issue seems to be non existent there but, there is extremely high cpu usage simply hovering over channels in discord, so possibly the issue is still there but less noticeable.

**Comment by khronokernel** [comment]
> only one dp port will work for the main monitor(in 5500xt it was dp 1, in 5600xt it is dp3)

I assume you've tested both `agdpmd=pikera` and `agdpmod=ignore` in boot-args for this? I also notice `iMacPro1,1` as your SMBIOS, it would be better suited to run `MacPro7,1` as the hardware would match up best with the SMBIOS. Would also be best to list your current version of macOS, I assume it's 10.15.6 as you have kernel version 19.6.0.

Another note is that 2005+ builds of macOS have support for iMac20,x which should include some misc fixes for Navi. The latest security update in Catalina should include this.

**Comment by KirillStomdevice** [comment]
did try the agdpmd args, macos version is 10.15.6, no updates available in software updates so i guess everything is installed.
will try to run macpro7,1 or imac20

**Comment by p1resmario** [comment]
System:
- Catalina 10.15.6
- X570 Gigabyte Aorus Ultra
- Ryzen 3800x
- RX 580 Shapphire Pulse

EFI Folder:
- https://www.dropbox.com/s/7l5l88yad329s6d/EFI.zip?dl=0

---

I'm having the same problem. Several other people too.
The cursor lag over links / text when cursor changes.

This is the link to a video demonstrating the problem:
https://www.dropbox.com/s/xn7n6bj90akqcqg/cursor-flickering.mp4?dl=0

---

It is also worth noting that when installing the OBS application, the problem stops. The reddit user "Ansonx10" showed this solution with the following observation:

"One solution is to install OBS and set up a Display Capture source with" Show Cursor "enabled. The way it captures the cursor for compositing is the key. I assume any software that does this (like remote desktop software) would have the same effect.

Adding the npci = 0x2000 boot argument (usually with disabling Above 4G Encoding) will make Mojave and Catalina behave more correctly, similar to High Sierra without the fix, and on High Sierra, it makes it work perfectly.

I use the GTX 760, and everything was perfect when I was using it with a Skylake CPU, but now that I've moved to a Zen 2 CPU (but still the same GTX 760), I have this problem. Possibly IGPU related since my new CPU doesn't have one, but I didn't have the issue even when the Skylage IGPU was disabled. "

---

That is, the problem seems to be related only to AMD processors. Since he used the same system before with Intel and the problem was not present.

**Comment by KirillStomdevice** [comment]
Tried the macpro7,1 with and without pikera arg, no change.
also couldn't find how to generate mac20,1/2/3 serail so cant really test that
solved the DP port issue, somehow whatevergreen was missing.

**Comment by p1resmario** [comment]
I tried **agdpmod=ignore** on mine and the system did not boot.

**Comment by PMheart** [comment]
Hello! Please post on forums for support.
