### ISSUE TITLE
autogenerate config.plist per cpu

### ISSUE THREAD

**Issue by rubydesign** [dortania/bugtracker#70]
This is a suggestion for the Desktop Guide (would be easier to have issues there?)

The issue is that users have to follow your (very good and precise) docs by hand.

The docs a clearly auto generated to remove duplication between the cpu's. This is as it should be, off course. And it would make it very easy to take the next step.

Suggestion: greate a downloadable config.plist for every cpu, that already includes all the edits that are descibed in the page.

Example: I have a i3-8100, so i follow https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html
This page describes what i need to do to the general config.plist
Would be easier if a config.plist with the required changes would be ready for download.

I am assuming that you use python the generate the docs. So one could just use python to generate the plist.

I would be happy to help, as a thanks for all your hard work.

**Comment by khronokernel** [comment]
> I am assuming that you use python the generate the docs. So one could just use python to generate the plist.

I do not, most docs in Dortania are written by me. There's nothing automated besides the conversion from markdown to html. 

And regarding premade config.plists, reason we wouldn't add them is due to 3 issues:

* OpenCore's configuration updates once a month, with some more mild while with others much more extreme. I already have to maintain the docs, adding the maintenance of 19 plists is extremely unreasonable
* Add to this that we have very specific settings even between vendors such as quirks relating to Asus's RHUB issues, having users skip over the entire section just to grab the plist at the end is a headache waiting to happen.
  * Then we add iGPU and dGPU settings, and now we have sometimes 5+ config.plists to maintain with just a single hardware gen
* Developers at Acidanthera have directly asked me to not include premade config.plists, mainly to avoid mismatches with OpenCore versions and mismatched info between the markdown files and config.plists. While we are 2 separate organizations, we still work closely together.


Our solution to this problem was [Slowgeek](https://opencore.slowgeek.com), as this site can more easily point out issues with ones config.plist without just auto fixing. It requires you to re-read the guide to properly understand what you need.

Hopefully this can help clarify our reason for no premade config files

**Comment by rubydesign** [comment]
Sorry for the late response, i just wanted to say thanks for your work
That there is no automation is surprising, so double thanks for doing it by hand.

I fully understand (and respect) the wishes of the developers. Though off course it is fantasy that we dumbos understand something that we copy paste. 
but that you for keeping the docs up to date, which allowed me to build a small mac mini clone. Btw, if you put up a paypal button, i'll happily press it.

And thanks for the slowgeek, it did pick up those inevitable mistakes
